In [1]:
import numpy as np

In [2]:
a = [2, 5, 7]

In [3]:
b = [3, 12, 27]

In [4]:
a+b

[2, 5, 7, 3, 12, 27]

In [5]:
c = [m+n for m, n in zip(a,b)]

In [6]:
c

[5, 17, 34]

In [11]:
sum(a)

14

Change to numpy Array

In [8]:
np_a = np.array(a)

In [9]:
np_b = np.array(b)

In [10]:
np_a + np_b

array([ 5, 17, 34])

In [ ]:
Only accept one datatype

In [11]:
p = np.array([1,2,"abc"])

In [12]:
p

array(['1', '2', 'abc'], dtype='<U11')

In [13]:
p+ np_a

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U11'), dtype('int32')) -> None

In [14]:
np_a.max()

7

In [15]:
np_a.mean()

4.666666666666667

In [16]:
np.ones(3)

array([1., 1., 1.])

In [17]:
np.zeros(3)

array([0., 0., 0.])

In [18]:
np_a*np.ones(3)

array([2., 5., 7.])

In [19]:
np_a*[3]

array([ 6, 15, 21])

In [20]:
np_a*np.array([2.2])

array([ 4.4, 11. , 15.4])

In [21]:
np_a*np.array([2.2,3.2])

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [22]:
np_a[1]

5

In [23]:
np_a[1:]

array([5, 7])

In [24]:
np_a[0:2]

array([2, 5])

In [25]:
np_2d = np.array([[1,2],[3,4]])

In [26]:
np_2d.sum()

10

In [27]:
np_2d.sum(axis=0)

array([4, 6])

In [28]:
np_2d.sum(axis=1)

array([3, 7])

In [29]:
np_2d.T()

TypeError: 'numpy.ndarray' object is not callable

In [30]:
np_2d.T

array([[1, 3],
       [2, 4]])

In [31]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [32]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [33]:
np_2d

array([[1, 2],
       [3, 4]])

In [34]:
np_2d+np.ones([2,2])

array([[2., 3.],
       [4., 5.]])

In [35]:
np_2d+np.ones(2)

array([[2., 3.],
       [4., 5.]])

In [36]:
np_2d+np.ones([2,1])

array([[2., 3.],
       [4., 5.]])

In [37]:
np_dotp = np_2d.dot(np.array([[1,10,100],[1000,100,10]]))

In [38]:
np_dotp

array([[2001,  210,  120],
       [4003,  430,  340]])

In [39]:
np_dotp[0,1]

210

In [40]:
np_dotp[1:3]

array([[4003,  430,  340]])

In [41]:
np_dotp[0:2,0]

array([2001, 4003])

In [42]:
np_rs = np.array([1,2,3,4,5,6])

In [43]:
np_rs

array([1, 2, 3, 4, 5, 6])

In [44]:
np_rs.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
np_rs.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [46]:
np_rs.reshape(3,-1)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [47]:
np_rs.reshape(4,-1)

ValueError: cannot reshape array of size 6 into shape (4,newaxis)

In [48]:
np_rs.reshape(2,-1)

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
np_rs.reshape(2,2,-1)

ValueError: cannot reshape array of size 6 into shape (2,2,newaxis)

In [50]:
np_rs.reshape(-1,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
np.random(2)

TypeError: 'module' object is not callable

In [52]:
np.random.random(2)

array([0.86068186, 0.33405765])

In [13]:
import numpy.random as random

In [17]:
random.random(2)

array([0.31763666, 0.43382899])

In [57]:
random.random([3,2])

array([[0.36616068, 0.87826345],
       [0.57232773, 0.51475234],
       [0.15084826, 0.9609286 ]])

In [19]:
#Take the inverse  of a matrix

import numpy.linalg as la

In [21]:
np_2d = la.inv(np_2d)

NameError: name 'np_2d' is not defined

In [60]:
la.eig(np_2d)

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [61]:
la.svd(np_2d)

(array([[-0.40455358, -0.9145143 ],
        [-0.9145143 ,  0.40455358]]),
 array([5.4649857 , 0.36596619]),
 array([[-0.57604844, -0.81741556],
        [ 0.81741556, -0.57604844]]))

In [62]:
la.pinv(np_2d)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [63]:
random.rand(2,3)*5

array([[0.85165135, 0.38385098, 3.61208594],
       [4.36352215, 4.42875448, 4.88972278]])

Random Number from a Normal distribution

In [64]:
random.randn(2,3)

array([[ 0.0224171 ,  0.39832923, -0.89096285],
       [-1.09459654,  0.01652856, -1.56037512]])

Random Number from an integer

In [65]:
random.randint(-2,3,5)

array([0, 0, 2, 2, 2])

In [66]:
random.shuffle(np_rs)

In [67]:
np_rs

array([3, 1, 6, 4, 2, 5])

Randomly pick two values from np_rs 

In [68]:
random.choice(np_rs, 2)

array([2, 3])

In [69]:
random.binomial(20,0.3)

6

Running a Binomial Distribution Probability of success is 0.3 for 20 trials. How many will i succeed in?

In [70]:
random.binomial(20, 0.3, 7)

array([ 5, 11,  6,  7,  4,  5,  3])

In [71]:
random.exponential(0.7,4)

array([0.63457411, 0.78383223, 3.16265054, 1.49534793])

In [72]:
%%time


UsageError: %%time is a cell magic, but the cell body is empty. Did you mean the line magic %time (single %)?


Running a Normal Distribution mean, standard deviation and give "3" output

In [73]:
random.normal(-5,12,3)

array([ 14.31142865, -14.67199768, -10.96458235])

In [74]:
random.logistic(-2,4,7)

array([-11.04250919,   1.1180365 ,   4.44174312,  -1.42912026,
         1.7706501 ,  -1.92472513,   3.23333616])

Shape of your distribution 

In [75]:
np_2d.shape

(2, 2)

In [76]:
np_2d.dtype

dtype('int32')

In [77]:
type(np_2d)

numpy.ndarray

In [78]:
np.vstack(np.ones([2,2]))

array([[1., 1.],
       [1., 1.]])

In [79]:
np.vstack((np_2d,np.ones([2,2])))

array([[1., 2.],
       [3., 4.],
       [1., 1.],
       [1., 1.]])

In [80]:
np.hstack((np_2d,np.ones([2,2])))

array([[1., 2., 1., 1.],
       [3., 4., 1., 1.]])

In [81]:
N=10000000
x=list(range(N))
y=list(range(N)) 
z=[]

In [82]:
np_x = np.array(x)
np_y = np.array(y)

In [83]:
%%time
for i in range(len(x)):
    z.append(x[i]+y[i])


CPU times: total: 2.98 s
Wall time: 4.03 s


In [84]:
%%time
np_z = np_x+np_y

CPU times: total: 15.6 ms
Wall time: 35.4 ms


In [85]:
import pandas as pd

In [86]:
numpy_df = pd.read_csv("NumpyExerciseData.csv")
numpy_df.head()

X0     X1     X2  X3  X4   X5   y  Unnamed: 7  Unnamed: 8  Unnamed: 9  \
0   1  5.768  62.55   0  28  2.6  28         NaN         NaN         NaN   
1   1  8.949  66.91   0  27 -2.0  46         NaN         NaN         NaN   
2   1  1.024  34.42   0  20 -3.4  14         NaN         NaN         NaN   
3   1  4.534  47.93   0  10  1.1  17         NaN         NaN         NaN   
4   1  8.641  35.26   0  30  3.8  32         NaN         NaN         NaN   

   Unnamed: 10  
0          NaN  
1          NaN  
2          NaN  
3          NaN  
4          NaN

In [91]:
numpy_df = numpy_df.drop("Unnamed: 7")
numpy_df.head()

KeyError: "['Unnamed: 7'] not found in axis"